### ISSUE TITLE
Checkboxes not reflected until a note is closed

### ISSUE THREAD

**Issue by microcreators** [turtl/tracker#145]
- have a list of checkboxes saved in a note
- open it again
- edit it
- mark one checkbox done [x] (because you cannot click it in the view mode... duh...)
- close the editor. **the checkbox is still not checked**.
- close the note. now the change is reflected.
thank you.

**Comment by orthecreedence** [comment]
Thanks for the report, I'll take a look at this when I get a moment. Ideally the boxes could just be checked from the note view and would save automatically without having to edit (obviously).

**Comment by l4mbd0x** [comment]
Please take a time to finish this feature. Because it will enable users to create truly interactive todo lists of whatever they want, which will facilitate for instance to use Turtl from places such as a markets where one will have a todo list of items to buy up to a company project todo list of tasks to be implemented. Whatever the scenario, this is very powerful and engaging for any user.

**Comment by orthecreedence** [comment]
This will definitely make it in. It's a somewhat complicated feature to implement, so it's going to be in v0.7.1 if all goes well with v0.7.0 (I really need to get 0.7.0 out the door).

**Comment by l4mbd0x** [comment]
What will the development of v0.7.0 need to finish @orthecreedence?

**Comment by orthecreedence** [comment]
There's one bug left (an obscure syncing bug, #175) which I think was the cause of one user's android client eating up 5gb of data that I want to fix before launch.

Other than that, I think v0.7.0 is more or less done. There are some things I want to do to the website (mainly so it points at the github release files since I'll no longer be hosting the installers directly on our website), and next week might be fairly busy for me so I am going to hold off on "launching" for now, but I'd say after fixing #175 rc14 is probably the version that will go live, and probably within a week.

**Comment by l4mbd0x** [comment]
Ok, will see if I can help with that.

**Comment by orthecreedence** [comment]
This specific issue is fixed and wll go out in v0.7.2. I considered making it so checkboxes can be changed/saved from the note view, but the feature is actually very complicated (it's really difficult to know which markdown checkbox corresponds to which checkbox in the note display).

I think the alternative here is to actually add a TODO/checklist note type (#42) which I've prioritized for v0.7.3.

**Comment by l4mbd0x** [comment]
Maybe the newest release of the markdown API changed the way they address check boxes. If so, it would help to distinguish one from the other.

**Comment by l4mbd0x** [comment]
@orthecreedence  is this the current API used for the checklist https://www.npmjs.com/package/markdown-it-checkbox?

**Comment by orthecreedence** [comment]
@lambd0x This is the one: `https://github.com/revin/markdown-it-task-lists`. I'm not married to it though. If the other one would work better for this issue, we can switch to that.

**Comment by orthecreedence** [comment]
Also, Moving this to #223 since it's a slightly different issue.

**Comment by l4mbd0x** [comment]
I didn't know https://github.com/revin/markdown-it-task-lists also made checklists. But yes, this one I found seems to ease things a bit in accordance to our objectives :).
