### ISSUE TITLE
Share feature only allows for space sharing over latest 0.7.x release

### ISSUE THREAD

**Issue by l4mbd0x** [turtl/tracker#159]
Using the latest 0.7.x release an user can share with a validated account a space to another user whose account is also validated, but cannot share anymore only one board with another user (regardless of the note amount). 

- The test bed has to have both parties using the latest release (previous releases were not tested).
- Maybe it would be commendable to verify which release broke the board sharing feature before fixing on the latest release for backlog purposes.

**Comment by orthecreedence** [comment]
This is by design, in the latest version only spaces can be shared, and boards are used to organize notes within spaces. I know this is a bit different from the previous version, but it simplifies things a lot (both for development and for users) and I think it makes sense.

At some point, we might add more granular sharing for Turtl, but for now only spaces can be shared.
