### ISSUE TITLE
Include the Turtl client in the Linux download

### ISSUE THREAD

**Issue by apatil** [turtl/tracker#169]
I'd love to use the CLI client at https://github.com/turtl/core_rs/tree/master/client . However, building it fails with

```bash
> make                                                                                                                        ~/Downloads/client
cargo build
   Compiling turtl_client v0.1.0 (file:///home/anand/Downloads/client)
error[E0463]: can't find crate for `turtl_core`
 --> src/main.rs:4:1
  |
4 | extern crate turtl_core;
  | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

even though make succeeds in core-rs itself and the relative path in cargo.toml seems legit as per https://stackoverflow.com/a/33025972.

Rather having random people like me try to build the client, what would you think about including it in https://turtlapp.com/releases/desktop/turtl-linux64-0.6.4.tar.bz2 .

**Comment by orthecreedence** [comment]
Right now, it's not even a cli per-se. It's more like a 
```
>
```
prompt and you have to know the exact [dispatch](https://github.com/turtl/core-rs/blob/master/src/dispatch.rs#L37) command (and args) you want to run. So it'd be like 

```
> user:login "user@email.com" "mypassword"
> sync:start
> profile:load
```
In other words, you have to have pretty intimate knowledge of the core in order to use it. It's really just for quick testing, and I recently made the core so it cannot be loaded as an rlib so that's why the build is failing (which I need to fix).

I'm going to track a separate ticket for the CLI here: https://github.com/turtl/tracker/issues/171
