### ISSUE TITLE
Docker hub image

### ISSUE THREAD

**Issue by huguesgr** [turtl/tracker#186]
The Dockerfile from turtl/server works like a charm.
Would you consider setting up an automatic build on the Docker hub?

**Comment by orthecreedence** [comment]
I can certainly look into this.

**Comment by halkeye** [comment]
I also would love this, especially cause I'm working on a kubernetes helm chart.

Do you need a hand with it at all?

**Comment by simonszu** [comment]
I'd love this as well. This shouldn't be too hard, at least to get a working prototype. I'm offering you any needed help as well.

**Comment by orthecreedence** [comment]
Actually, some guidance here would be nice. I haven't used Docker hub much. If anyone has a guide or instructions on setting up an automated build, that'd be great.

**Comment by simonszu** [comment]
No problem.
Connect your Github account with docker hub. Create a new automated build. It will list all your Github repos then. Select the one you want. That's all.
It will use the repo's Readme as the image's Readme. You can also select another image (usually the used base image) as a trigger for rebuild as well.

Its a crude form of CI, which will trigger a docker build on docker hub each time you push your repo on master or when the underlying base image builds.

I cannot point you to the location where you can find the settings for Github connection or so, since docker hub had a major UI overhaul recently which changed the UI what I was used to. But I can have a look into it tomorrow.

**Comment by simonszu** [comment]
OK, since there is no real progress, i have set up a quick and dirty CI job on my own Jenkins. It pulls the repo each night, builds the image, and pushes it to https://cloud.docker.com/repository/docker/simonszu/turtl. The tags increment with the Jenkins build number. 

Feel free to use it.

**Comment by orthecreedence** [comment]
Thanks for the instructions! I think this is set up now: https://cloud.docker.com/repository/docker/orthecreedence/turtl-server

**Comment by halkeye** [comment]
For future people, the url is https://hub.docker.com/r/orthecreedence/turtl-server
