### ISSUE TITLE
Connection failed -- Error: column "last_login" of relation "users" does not exist

### ISSUE THREAD

**Issue by mic301** [turtl/tracker#187]
Hi,

Like the title says, I have a error message when i try to connect to the turtl server (https://apiv3.turtlapp.com), since the publishing of the last release (0.7.0), On the v0.7.0 like on the v0.7.0-rc15, desktop or Android version, I have the same error :

_Connection failed -- Error: column "last_login" of relation "users" does not exist_

I supposed it's a server-side issue.

On the last version, I had to migrate my data to the newer server version, and change the name of my user account in the operation. Something like : userName => userMail. This association do not works, since the last release.

So :
- Do I have to use my older ID account (userName) ? 
- This operation could it replace my newer data by the older ones ?

Best regards

**Comment by Tiemichael** [comment]
Same here ..
After upgrading the server, Android, and WIN-Desktop just now,  I cannot login

Login failed -- Error: column "last_login" of relation "users" does not exist

**Comment by l4mbd0x** [comment]
I've been using the rc-13 of 0.7.0 and it was working "Login included." However, alike to @Tiemichael  and @mic301 now the title of this issue is displayed whenever I try to login.

This error is indeed on the server side because today at 7am BRT timezone it was logging in/out without problems for the rc-13 that I have installed on my Linux box.

Also, I tried installing/uninstalling for the final release of 0.7.0 and also the rc-{15,14} and all of them fails with the same error for the log in.
Likewise, I suppose all the remainder rc releases will likely also fail (I have not tested the rest, though).

@mic301 This error is not specific to your account migration from the v0.6.4 to v0.7.0 because I also migrated from the same version and this error is identical for me too. Don't create a new account just yet, if you do it, then you won't be able to recover the data from the previously imported account That's because this data can only be accessible through your access only. Hence, requiring the server side issue to be solved.

**Comment by simplyandyg** [comment]
I just updated to the latest app on Android and my Mac and I am running into this same error when migrating over my account.

[screenshot of the error](https://ibb.co/i7Q0Dp)

**Comment by orthecreedence** [comment]
Sorry, everyone. We had an issue with our database last night. This should be fixed now.

**Comment by mic301** [comment]
My data say thank to you! :)
