### ISSUE TITLE
Android only - Turtl doesn't hold the session across multiple apps

### ISSUE THREAD

**Issue by l4mbd0x** [turtl/tracker#224]
Over the latest release of Turtl for Android. If an user opens up a note and opens up a browser session (I experienced this using chrome), and then returns to the opened session of Turtl. It will have exited the note and the session. Then Turtl will automatically login with the server again as if nothing happened. (If the user had unsaved edits it is lost too).

**Comment by orthecreedence** [comment]
This is the android OS killing the app to free up memory. There's actually not much we can do about it specifically, but there are some workarounds.

- Unsaved edits would be fixed by this: #40 (coming in v0.7.3)
- Running the core in a background service would allow pulling up the last state without logging back in: #168 

So for now I think those two cover this ticket (going to close).
