### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by filisko** [turtl/tracker#241]
Hello guys,
Would it be very difficult to implement and support a LDAP authentication system? Maybe as a plugin?

Regards,
Filis.

**Comment by orthecreedence** [comment]
I've spent about half an hour researching this, and the answer is "I don't know."

I don't know how LDAP works, how it authenticates users, or much about the protocol at all. If you know more about this, I would greatly appreciate the input.

As a reference, here's how users are currently authenticated:

1. the user types their username/password and hits "login"
1. the app generates a cryptographic key from their username/password, and uses this key to encrypt a string value that is then sent to the server (along with their username (email address)). this encrypted value is the authentication token.
1. the server looks up the user by email, and if it finds them, it hashes the authentication token generated by the client and compares it (via double-hmac) to the authentication token stored in the user's database record
1. if the hashed tokens match, the user is successfully authenticated.

So at the time of authentication, we have their username (email address) and what would appear to be a random token that could only be generated if you knew their username/password.

I'm guessing that token would not be suitable to perform LDAP authentication, and the client would have to send some other kind of token (on top of the Turtl auth token) that could be used for LDAP auth. My only worry is this: from my (limited) understanding, LDAP acts as sort of a central place user accounts live, and if you change your password there, it changes it everywhere. However, with Turtl, the key that unlocks your entire profile is generated from your password, which the server has no access to.

So if a user were to change their LDAP password, this would allow them to authenticate with the new password via Turtl, but they would still need to know their old password in order to decrypt their profile (and this would somehow have to be noted in the UI: "Your LDAP password changed, but enter your old password in order to decrypt your profile").

This is all based off of assumptions I have of LDAP, though, and I would love any kind of correction here (or just more information in general).

**Comment by filisko** [comment]
Hi @orthecreedence,
I was really interested in how Turtl's login works and you described it quite well.

> My only worry is this: from my (limited) understanding, LDAP acts as sort of a central place user accounts live, and if you change your password there, it changes it everywhere.

If you change your password there, next time you try to login in your service, your service will just try to perform the authentication as usual connecting to LDAP server and trying to match user/password.

But yes, I see that the thing here is the token.

> So if a user were to change their LDAP password, this would allow them to authenticate with the new password via Turtl, but they would still need to know their old password in order to decrypt their profile (and this would somehow have to be noted in the UI: "Your LDAP password changed, but enter your old password in order to decrypt your profile").

You mean that we would send the username and password just for the LDAP authentication because LDAP requires passwords, right? And once we're in and we 'recreate' the token and if it's different from the one in the server, we alert the user, right?

I think that this would be the only way if we're working with tokens. Yes.

**Comment by orthecreedence** [comment]
> You mean that we would send the username and password just for the LDAP authentication because LDAP requires passwords, right? And once we're in and we 'recreate' the token and if it's different from the one in the server, we alert the user, right?

I think so? Except right now, the server doesn't have any knowledge of a user's password...it's never sent to the server at all.

What I'm really trying to say is that yes, it's more than likely possible for the server to authenticate users with LDAP, but authentication is only half the problem because they still need a key to decrypt their profile. That key currently is generated on the client, and the entire structure of the app depends on the client being the one generating that key. So if the user's LDAP password is changed (outside of the Turtl app) then the LDAP authentication of the user would be out of sync with the user's decryption key, and the user would have to sync them back up by entering a) their new password to authenticate and b) their old password to generate the decryption key.

So there's some definite complication here surrounding the login flow if this were to be implemented.

When authenticating with LDAP in general, do you send a username/password in plaintext?

**Comment by filisko** [comment]
I see.
What is usually used to authenticate is a 'base DN' along with the 'user filter'. Those two values are used to make the 'user finding', once you find it, you get the 'full' DN of the found user and then perform a LDAP bind operation which is users DN + user password

* Base DN look like: **ou=users,dc=server,dc=com**
* User filters look like: **(&(posixAccount=user)(uid=%uid))** (here %uid would be replaced by username)

But yes, you send everything in plain mode to the server.

**Comment by orthecreedence** [comment]
Got it! Thanks for the explanation.

Here's the thing. It's fairly core to Turtl to not send the plaintext password from the client to the server, the idea being that the server should *never* have enough information to decrypt the user's data. So the client doesn't send the password or the generated key, just a token that only someone with the proper password would be able to generate so the server can verify the user is who they claim to be.

If there's some way to authenticate a user in LDAP without the password (say, maybe using the password to generate a value with PBKDF2 that LDAP can confirm without direct password access), then this might be possible.

However, the moment the client sends the user's plaintext password to the server, Turtl is no longer Turtl, it becomes any number of unencrypted note apps (Evernote, Keep, etc). So while I'd *like* to support this as a possible feature (via a server plugin) I can't justify putting code into the client that would send the password to the server, even if it was off by default and needed a config option to turn it on.

Hopefully that all makes sense, please let me know if I'm missing something. I'm going to close this issue for now, but that doesn't mean I won't be responding to questions or ideas on this ticket...if it turns out this can be done in a way that works withing Turtl's privacy/security framework, we can open this back up.

**Comment by filisko** [comment]
Thanks for considering it.
So I see that it would have to touch the core of the app that way. That's why I was wondering about the Plugins system flexibility so we don't have to touch any core at all and not compromise Turtl's 'way'.

I hope someone push into this 😄
It would be nice to have Turtl as note taking system for a company that uses LDAP.

**Comment by orthecreedence** [comment]
I could see this being useful for a lot of companies who want to use Turtl internally. Maybe there will be a version eventually that makes compromises to allow this to happen.

I will certainly keep this feature in mind.

**Comment by kasioumis** [comment]
Single Sign-On (SSO) would indeed be a very interesting feature for turtl! Maybe an integration with [Passport](http://www.passportjs.org/) would be a feasible compromise to allow for local authentication as well as provided-based authentication (LDAP, GitHub, OAuth, etc)? For example we've used [Wiki.js's authentication](https://github.com/Requarks/wiki/blob/master/server/core/auth.js) with a [custom provider](https://github.com/Requarks/wiki/tree/master/server/modules/authentication), similarly based on Node.js.

**Comment by filisko** [comment]
That looks interesting @kasioumis, let's see what @orthecreedence thinks, he is the main developer of Turtl.
