### ISSUE TITLE
Turtl server with MySQL

### ISSUE THREAD

**Issue by hermann-san** [turtl/tracker#296]
I'd like to install the Turtl server for me and my Family, but my shared hoster doesn't have a managed Postgre DB. Installing, configuring and maintaining Postgre is not an option to me at the moment since I've not much experience setting up DB's. 
With MySQL this would be much easier for me to setup and maintain ( I suppose) since my shared hoster has setup MySQL already. 
Is there a specific reason why MySQL has not been taken as a DB?
I assume Postgre has better performance on large installations.

**Comment by orthecreedence** [comment]
I have much more experience with tuning, scaling, and operating Postgres since I've been using it professionally for the past 6+ years and haven't really touched MySQL in any production capacity since before then. Also, because nodejs is used as the platform for Turtl's server, I figured database choice wouldn't be an issue since most shared hosting only supports PHP (not node) so likely people will be installing in container services or on VPSs.

I don't want to use an ORM because I've only ever had bad experiences with them and they *never* fulfill their promises, so I think for now Postgres is the only option and it will likely stay that way for quite some time.

The only real advice I can give is to use a $5/mo Droplet or Linode box and install the server there. For personal usage you won't need much more than the cheapest VPS.

**Comment by hermann-san** [comment]
Thanks for your explanation. 
My shared hoster does support node.  Using Droplet or Linode would also require me to look into the other technology where I don't have experience with, I would have to pay some extra money to what I already have and there is the database maintenance task which I currently don't have with my shared hoster.
These are the reasons why I will currently not going install Turtle server, even though I'd really like to.
ORM means MySQL and alike? The advantage is that it is so widely used and that makes it easy for the (no so experienced) admin.
These are just a few thoughts I have about this and I do understand the points you've made.
I hope that someone would write a tutorial for my (popular) shared hoster Uberspace.de on how to install and maintain a Turtl server.
