### ISSUE TITLE
Fail2Ban config

### ISSUE THREAD

**Issue by bytersproblem** [turtl/tracker#340]
Hello and thanks for this beautiful piece of software.
Since I am not a tech wiz (bun can find my way if correctly guided) I am looking for the step by step solution to setup fail2ban service for Turtl notes. Any help would be greatly appreciated.

**Comment by rubbingalcoholic** [comment]
Are you looking at running the Turtl server yourself? If not, you shouldn't need to worry about running fail2ban since the notes are stored encrypted on the Turtl server. The desktop client has no daemon running with open ports.

In general, the most effective attack against our service would be a DDoS. Due to the level of security that goes into our encryption, it would not be realistic to mount a brute force attack against a typical user account. Fail2ban would not help in a DDoS scenario though.

I'm going to close this as the server ops configuration is beyond the scope of what we do, but if you or someone can recommend a fail2ban configuration for the server we'll gladly add it to our documentation.
