### ISSUE TITLE
Can't login anymore on Android app

### ISSUE THREAD

**Issue by TronFortyTwo** [turtl/tracker#344]
I use the Android app, and I can't login anymore.

Steps to reproduce
- Open the app, and in the login page put email and password
- The app says I have to migrate my account from v2 to v3 but I was already using protocol v3. If I start the migration progress the app reports that the accounts is already existing so it stop the migration process. In the end, I can no longer access my account.

I can provide any info you need, logs. I can provide also sensitive information that can be useful in some non public way.

Thanks for the support! :)

**Comment by orthecreedence** [comment]
@TronFortyTwo How long was the app working before it stopped? If you want to debug further, email me at andrew@turtlapp.com. It might be helpful to send logs to me (on the login screen: Three dots menu -> Debug log). Thanks!

**Comment by TronFortyTwo** [comment]
Quite a bit of time (few months). Then I erased local data and this started happening. Strangely, I tried on linux desktop app and it works. Thanks, I'll send the log with email.

**Comment by orthecreedence** [comment]
Can you open the login screen, open "Advanced settings" and tell me what you have in the "Old Turtl server" and "Turtl server" fields? From the log you sent me it looks like it's talking to the old server instead of the new one for the primary login.

**Comment by TronFortyTwo** [comment]
This is what I see
![Screenshot_20191117-215440_Turtl](https://user-images.githubusercontent.com/18293963/69013839-f17c2700-0984-11ea-94b7-c365d5d42e98.png)

**Comment by orthecreedence** [comment]
Weird, `https://apiv3.turtlapp.com` is the correct server. If you open that URL in a browser on your phone do you get a response? I'm wondering if it's blocked for some reason, and that's why it's trying to talk to the old API. But then again, you said that it tries to migrate and then says the account already exists? Which means the new server must be up. The only thing I can think of is that the auth is incorrect. Are you sure you're using your new password to log in and not the old password (the one associated with the old server pre-migration)?

**Comment by TronFortyTwo** [comment]
Yes, it was the password wrong, I'll save you from explaining why. Very sorry I have made you lose time, but it is misleading that on wrong password you got redirected to the migration page.

**Comment by orthecreedence** [comment]
Yeah, the migration process, although ultimately needed, has definitely caused us some headaches. I'm glad you got access to your account!
